spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: szy199601
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081

jwt:
  expire: 3600000
  secret: szy*199601
  encryptType: HS256

file:
  upload:
    picPath: D:\projects\blogs\blog-backend\uploadImg
    picBaseUrl: http://192.168.1.19:8081/uploadImg/
    filePath: D:\projects\blogs\blog-backend\uploadFiles
    fileBaseUrl: http://192.168.1.19:8081/uploadFile/